2018-06-14 12:01:00 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=19 from 2018-06-14 11:59:33.237021)
2018-06-14 12:01:02 ERROR (Thread-6) [xiaomi_gateway] Got error element in data {"error":"No device"}
2018-06-14 12:01:02 ERROR (Thread-6) [xiaomi_gateway] Got error element in data {"error":"No device"}
2018-06-14 12:01:02 ERROR (Thread-6) [xiaomi_gateway] Not a valid device. Check the mac adress and update the firmware.
2018-06-14 12:01:17 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:01:33 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:01:49 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:03:14 WARNING (Thread-23) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-14 12:03:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:03:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:03:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:04:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:04:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:04:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:04:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:05:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:05:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:05:31 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 502, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 466, in log
    for key, value in fmt_info:
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 458, in <genexpr>
    for key, method in self._methods)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 416, in _format_a
    ip = request.remote
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 504, in __get__
    val = self.wrapped(inst)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_request.py", line 332, in remote
    peername = self.transport.get_extra_info('peername')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 546, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2018-06-14 12:05:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:05:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:06:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:06:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:06:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:07:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:07:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:07:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:07:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:08:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:08:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:08:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:08:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:09:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:09:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:09:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:09:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:10:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:10:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:10:43 WARNING (MainThread) [homeassistant.components.script] Script script.thongbaohoan already running.
2018-06-14 12:10:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:10:50 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 502, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 466, in log
    for key, value in fmt_info:
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 458, in <genexpr>
    for key, method in self._methods)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 416, in _format_a
    ip = request.remote
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 504, in __get__
    val = self.wrapped(inst)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_request.py", line 332, in remote
    peername = self.transport.get_extra_info('peername')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 546, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2018-06-14 12:11:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:11:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:11:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:11:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:12:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:12:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:12:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:12:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:13:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:13:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:13:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:13:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:14:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:14:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:14:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:15:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:15:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:15:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:15:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:16:00 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 502, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 466, in log
    for key, value in fmt_info:
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 458, in <genexpr>
    for key, method in self._methods)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 416, in _format_a
    ip = request.remote
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 504, in __get__
    val = self.wrapped(inst)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_request.py", line 332, in remote
    peername = self.transport.get_extra_info('peername')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 546, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2018-06-14 12:16:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:16:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:16:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:16:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:17:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:17:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:17:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:17:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:18:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:18:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:18:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:19:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:19:12 WARNING (MainThread) [homeassistant.components.group] remove:Group 'all_automations' doesn't exist!
2018-06-14 12:19:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:19:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:19:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:20:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:20:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:20:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:20:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:21:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:21:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:21:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:21:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:22:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:22:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:22:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:23:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:23:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:23:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:23:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:24:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:24:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:24:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:24:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:25:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:25:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:25:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:25:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:26:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:26:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:26:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:27:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:27:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:27:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:27:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:28:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:28:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:28:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:28:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:29:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:29:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:29:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:29:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:30:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:30:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:30:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:31:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:31:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:31:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:31:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:32:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:32:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:32:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:32:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:33:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:33:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:33:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:33:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:34:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:34:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:34:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:35:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:35:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:35:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:35:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:36:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:36:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:36:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:36:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:37:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:37:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:37:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:37:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:38:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:38:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:38:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:39:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:39:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:39:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:39:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:40:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:40:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:40:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:40:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:41:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:41:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:41:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:41:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:42:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:42:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:42:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:43:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:43:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:43:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:43:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:44:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:44:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-14 12:44:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
